# Generated by Django 5.1.2 on 2025-12-31 13:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_doctor'),
    ]

    operations = [
        migrations.CreateModel(
            name='Patient',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('national_number', models.CharField(max_length=20, unique=True)),
                ('name', models.CharField(max_length=255)),
                ('birth_date', models.DateField()),
                ('gender', models.CharField(max_length=10)),
                ('residence_lat', models.FloatField()),
                ('residence_long', models.FloatField()),
                ('work_lat', models.FloatField()),
                ('work_long', models.FloatField()),
            ],
        ),
    ]
