# Generated by Django 5.1.2 on 2025-12-31 13:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_patient'),
    ]

    operations = [
        migrations.CreateModel(
            name='Disease',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('disease_code', models.CharField(max_length=50)),
                ('name', models.CharField(max_length=255)),
                ('type', models.CharField(max_length=100)),
                ('transmission_vector', models.CharField(max_length=100)),
                ('symptoms', models.TextField()),
                ('risk_level', models.IntegerField()),
                ('infection_score', models.FloatField()),
            ],
        ),
    ]
