# Generated by Django 5.1.2 on 2025-12-31 14:25

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0007_geodata'),
    ]

    operations = [
        migrations.CreateModel(
            name='GeoCluster',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('center_lat', models.FloatField()),
                ('center_long', models.FloatField()),
                ('radius', models.FloatField()),
                ('case_count', models.IntegerField()),
                ('risk_level', models.IntegerField()),
                ('generated_at', models.DateTimeField(auto_now_add=True)),
                ('disease', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.disease')),
            ],
        ),
    ]
