# Generated by Django 5.1.2 on 2025-12-31 15:15

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0008_geocluster'),
    ]

    operations = [
        migrations.CreateModel(
            name='Report',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('generated_at', models.DateTimeField(auto_now_add=True)),
                ('region', models.CharField(max_length=255)),
                ('region_type', models.CharField(max_length=50)),
                ('summary', models.TextField()),
                ('risk_score', models.FloatField()),
                ('spread_map_url', models.URLField()),
                ('disease', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.disease')),
            ],
        ),
    ]
