# Generated by Django 5.1.2 on 2025-12-31 16:02

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0010_medicalhistory'),
    ]

    operations = [
        migrations.CreateModel(
            name='Allergy',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('allergy_name', models.CharField(max_length=255)),
                ('severity_level', models.CharField(max_length=50)),
                ('history', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.medicalhistory')),
            ],
        ),
        migrations.CreateModel(
            name='chronicDisease',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('disease_name', models.CharField(max_length=255)),
                ('diagnosis_date', models.DateField()),
                ('history', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.medicalhistory')),
            ],
        ),
        migrations.CreateModel(
            name='SurgicalHistory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('surgery_description', models.CharField(max_length=255)),
                ('surgery_date', models.DateField()),
                ('has_metal_plates', models.BooleanField(default=False)),
                ('history', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.medicalhistory')),
            ],
        ),
        migrations.CreateModel(
            name='Vaccine',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('vaccine_name', models.CharField(max_length=255)),
                ('date_administered', models.DateField()),
                ('history', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.medicalhistory')),
            ],
        ),
    ]
