# Generated by Django 5.2.9 on 2026-04-08 04:49

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0011_allergy_chronicdisease_surgicalhistory_vaccine'),
    ]

    operations = [
        migrations.CreateModel(
            name='LabTest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('test_code', models.CharField(max_length=100)),
                ('test_name', models.CharField(max_length=255)),
                ('result', models.TextField()),
                ('test_date', models.DateTimeField()),
                ('notes', models.TextField(blank=True)),
                ('visit', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.visit')),
            ],
        ),
    ]
