# Generated by Django 5.2.9 on 2026-04-08 04:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0012_labtest'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='labtest',
            table='LAB_TESTS',
        ),
    ]
