# Generated by Django 5.2.9 on 2026-04-12 05:39

import datetime
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0013_alter_labtest_table'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='report',
            options={'ordering': ('-generated_at',)},
        ),
        migrations.RemoveField(
            model_name='report',
            name='region',
        ),
        migrations.RemoveField(
            model_name='report',
            name='region_type',
        ),
        migrations.RemoveField(
            model_name='report',
            name='spread_map_url',
        ),
        migrations.AddField(
            model_name='report',
            name='alert_level',
            field=models.CharField(choices=[('low', 'Low'), ('medium', 'Medium'), ('high', 'High'), ('critical', 'Critical')], default='low', max_length=20),
        ),
        migrations.AddField(
            model_name='report',
            name='analysis_period_end',
            field=models.DateField(default=datetime.date.today),
        ),
        migrations.AddField(
            model_name='report',
            name='analysis_period_start',
            field=models.DateField(default=datetime.date.today),
        ),
        migrations.AddField(
            model_name='report',
            name='current_case_count',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='report',
            name='growth_rate',
            field=models.FloatField(default=0),
        ),
        migrations.AddField(
            model_name='report',
            name='nearby_case_count',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='report',
            name='previous_case_count',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='report',
            name='reasons',
            field=models.JSONField(blank=True, default=list),
        ),
        migrations.AddField(
            model_name='report',
            name='status',
            field=models.CharField(choices=[('new', 'New'), ('reviewed', 'Reviewed'), ('resolved', 'Resolved'), ('archived', 'Archived')], default='new', max_length=20),
        ),
        migrations.AddField(
            model_name='report',
            name='surge_ratio',
            field=models.FloatField(default=0),
        ),
        migrations.AddField(
            model_name='report',
            name='trigger_visit',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='reports', to='core.visit'),
        ),
        migrations.AlterField(
            model_name='report',
            name='disease',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reports', to='core.disease'),
        ),
    ]
