# Generated by Django 5.2.9 on 2026-04-14 06:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0014_alter_report_options_remove_report_region_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='disease',
            options={'ordering': ('name',)},
        ),
        migrations.AddField(
            model_name='disease',
            name='high_priority',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='disease',
            name='is_reference',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='disease',
            name='policy_profile',
            field=models.CharField(choices=[('general', 'General'), ('high_priority', 'High Priority'), ('rare', 'Rare'), ('cluster_sensitive', 'Cluster Sensitive'), ('surge_sensitive', 'Surge Sensitive'), ('environmental_signal', 'Environmental Signal')], default='general', max_length=50),
        ),
        migrations.AddField(
            model_name='disease',
            name='rare_disease',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='disease',
            name='source_name',
            field=models.CharField(blank=True, default='', max_length=100),
        ),
        migrations.AddField(
            model_name='disease',
            name='source_record_id',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='disease',
            name='disease_code',
            field=models.CharField(db_index=True, max_length=50, unique=True),
        ),
    ]
