# Generated by Django 5.2.9 on 2026-04-21 04:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0015_alter_disease_options_disease_high_priority_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='visit',
            name='diagnose',
            field=models.TextField(blank=True, default=''),
        ),
    ]
