# Generated by Django 5.2.9 on 2026-04-26 12:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0022_medicalhistory_patient_onetoone'),
    ]

    operations = [
        migrations.AlterField(
            model_name='patient',
            name='residence_lat',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='patient',
            name='residence_long',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='patient',
            name='work_lat',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='patient',
            name='work_long',
            field=models.FloatField(blank=True, null=True),
        ),
    ]
