# Generated by Django 5.2.9 on 2026-05-05 03:56

from django.db import migrations, models


def trust_existing_active_users(apps, schema_editor):
    User = apps.get_model("core", "User")
    User.objects.filter(is_active=True).update(
        email_verified=True,
        admin_approved=True,
    )


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0024_emailverificationcode'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='admin_approved',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='user',
            name='email_verified',
            field=models.BooleanField(default=False),
        ),
        migrations.RunPython(
            trust_existing_active_users,
            migrations.RunPython.noop,
        ),
    ]
