# Generated by Django 5.2.9 on 2026-05-27 17:58

import django.core.validators
import django.db.models.functions.text
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
        ('core', '0028_visit_marital_status_widow'),
    ]

    operations = [
        migrations.AlterField(
            model_name='disease',
            name='infection_score',
            field=models.FloatField(validators=[django.core.validators.MinValueValidator(0)]),
        ),
        migrations.AlterField(
            model_name='disease',
            name='risk_level',
            field=models.IntegerField(validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(5)]),
        ),
        migrations.AlterField(
            model_name='geocluster',
            name='case_count',
            field=models.IntegerField(validators=[django.core.validators.MinValueValidator(0)]),
        ),
        migrations.AlterField(
            model_name='geocluster',
            name='center_lat',
            field=models.FloatField(validators=[django.core.validators.MinValueValidator(-90), django.core.validators.MaxValueValidator(90)]),
        ),
        migrations.AlterField(
            model_name='geocluster',
            name='center_long',
            field=models.FloatField(validators=[django.core.validators.MinValueValidator(-180), django.core.validators.MaxValueValidator(180)]),
        ),
        migrations.AlterField(
            model_name='geocluster',
            name='radius',
            field=models.FloatField(validators=[django.core.validators.MinValueValidator(0)]),
        ),
        migrations.AlterField(
            model_name='geocluster',
            name='risk_level',
            field=models.IntegerField(validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(5)]),
        ),
        migrations.AlterField(
            model_name='geodata',
            name='latitude',
            field=models.FloatField(validators=[django.core.validators.MinValueValidator(-90), django.core.validators.MaxValueValidator(90)]),
        ),
        migrations.AlterField(
            model_name='geodata',
            name='longitude',
            field=models.FloatField(validators=[django.core.validators.MinValueValidator(-180), django.core.validators.MaxValueValidator(180)]),
        ),
        migrations.AlterField(
            model_name='hospital',
            name='hospital_lat',
            field=models.FloatField(validators=[django.core.validators.MinValueValidator(-90), django.core.validators.MaxValueValidator(90)]),
        ),
        migrations.AlterField(
            model_name='hospital',
            name='hospital_long',
            field=models.FloatField(validators=[django.core.validators.MinValueValidator(-180), django.core.validators.MaxValueValidator(180)]),
        ),
        migrations.AlterField(
            model_name='patient',
            name='residence_lat',
            field=models.FloatField(blank=True, null=True, validators=[django.core.validators.MinValueValidator(-90), django.core.validators.MaxValueValidator(90)]),
        ),
        migrations.AlterField(
            model_name='patient',
            name='residence_long',
            field=models.FloatField(blank=True, null=True, validators=[django.core.validators.MinValueValidator(-180), django.core.validators.MaxValueValidator(180)]),
        ),
        migrations.AlterField(
            model_name='patient',
            name='work_lat',
            field=models.FloatField(blank=True, null=True, validators=[django.core.validators.MinValueValidator(-90), django.core.validators.MaxValueValidator(90)]),
        ),
        migrations.AlterField(
            model_name='patient',
            name='work_long',
            field=models.FloatField(blank=True, null=True, validators=[django.core.validators.MinValueValidator(-180), django.core.validators.MaxValueValidator(180)]),
        ),
        migrations.AlterField(
            model_name='visit',
            name='height',
            field=models.FloatField(validators=[django.core.validators.MinValueValidator(30), django.core.validators.MaxValueValidator(250)]),
        ),
        migrations.AlterField(
            model_name='visit',
            name='weight',
            field=models.FloatField(validators=[django.core.validators.MinValueValidator(0.1), django.core.validators.MaxValueValidator(500)]),
        ),
        migrations.AddConstraint(
            model_name='disease',
            constraint=models.CheckConstraint(condition=models.Q(('risk_level__gte', 0), ('risk_level__lte', 5)), name='core_disease_risk_level_0_5'),
        ),
        migrations.AddConstraint(
            model_name='disease',
            constraint=models.CheckConstraint(condition=models.Q(('infection_score__gte', 0)), name='core_disease_infection_score_non_negative'),
        ),
        migrations.AddConstraint(
            model_name='geocluster',
            constraint=models.CheckConstraint(condition=models.Q(('center_lat__gte', -90), ('center_lat__lte', 90)), name='core_geocluster_center_lat_valid'),
        ),
        migrations.AddConstraint(
            model_name='geocluster',
            constraint=models.CheckConstraint(condition=models.Q(('center_long__gte', -180), ('center_long__lte', 180)), name='core_geocluster_center_long_valid'),
        ),
        migrations.AddConstraint(
            model_name='geocluster',
            constraint=models.CheckConstraint(condition=models.Q(('radius__gte', 0)), name='core_geocluster_radius_non_negative'),
        ),
        migrations.AddConstraint(
            model_name='geocluster',
            constraint=models.CheckConstraint(condition=models.Q(('case_count__gte', 0)), name='core_geocluster_case_count_non_negative'),
        ),
        migrations.AddConstraint(
            model_name='geocluster',
            constraint=models.CheckConstraint(condition=models.Q(('risk_level__gte', 0), ('risk_level__lte', 5)), name='core_geocluster_risk_level_0_5'),
        ),
        migrations.AddConstraint(
            model_name='geodata',
            constraint=models.CheckConstraint(condition=models.Q(('latitude__gte', -90), ('latitude__lte', 90)), name='core_geodata_latitude_valid'),
        ),
        migrations.AddConstraint(
            model_name='geodata',
            constraint=models.CheckConstraint(condition=models.Q(('longitude__gte', -180), ('longitude__lte', 180)), name='core_geodata_longitude_valid'),
        ),
        migrations.AddConstraint(
            model_name='hospital',
            constraint=models.CheckConstraint(condition=models.Q(('hospital_lat__gte', -90), ('hospital_lat__lte', 90)), name='core_hospital_lat_valid'),
        ),
        migrations.AddConstraint(
            model_name='hospital',
            constraint=models.CheckConstraint(condition=models.Q(('hospital_long__gte', -180), ('hospital_long__lte', 180)), name='core_hospital_long_valid'),
        ),
        migrations.AddConstraint(
            model_name='patient',
            constraint=models.CheckConstraint(condition=models.Q(('residence_lat__isnull', True), models.Q(('residence_lat__gte', -90), ('residence_lat__lte', 90)), _connector='OR'), name='core_patient_residence_lat_valid'),
        ),
        migrations.AddConstraint(
            model_name='patient',
            constraint=models.CheckConstraint(condition=models.Q(('residence_long__isnull', True), models.Q(('residence_long__gte', -180), ('residence_long__lte', 180)), _connector='OR'), name='core_patient_residence_long_valid'),
        ),
        migrations.AddConstraint(
            model_name='patient',
            constraint=models.CheckConstraint(condition=models.Q(('work_lat__isnull', True), models.Q(('work_lat__gte', -90), ('work_lat__lte', 90)), _connector='OR'), name='core_patient_work_lat_valid'),
        ),
        migrations.AddConstraint(
            model_name='patient',
            constraint=models.CheckConstraint(condition=models.Q(('work_long__isnull', True), models.Q(('work_long__gte', -180), ('work_long__lte', 180)), _connector='OR'), name='core_patient_work_long_valid'),
        ),
        migrations.AddConstraint(
            model_name='user',
            constraint=models.UniqueConstraint(django.db.models.functions.text.Lower('email'), condition=models.Q(('email', ''), _negated=True), name='core_user_unique_email_ci_not_blank'),
        ),
        migrations.AddConstraint(
            model_name='visit',
            constraint=models.CheckConstraint(condition=models.Q(('weight__gt', 0), ('weight__lte', 500)), name='core_visit_weight_valid'),
        ),
        migrations.AddConstraint(
            model_name='visit',
            constraint=models.CheckConstraint(condition=models.Q(('height__gte', 30), ('height__lte', 250)), name='core_visit_height_valid'),
        ),
    ]
