# Generated by Django 5.2.9 on 2026-06-29 21:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0030_auditlog'),
    ]

    operations = [
        migrations.AddField(
            model_name='supportmessage',
            name='status',
            field=models.CharField(choices=[('sent', 'تم الإرسال'), ('delivered', 'تم الاستلام'), ('read', 'تمت القراءة')], default='sent', max_length=20),
        ),
    ]
